### ISSUE TITLE
demo instruction? 

### ISSUE THREAD

**Issue by JudyYe** [uiuc-robovision/hands-as-probes#1]
Dear authors,

Thank you for your great work and efforts in reproducing the training and evaluation process. However, I wonder if you could release the pretrained model and provide some demo instruction to run it? Thank you!

**Comment by mohit1997** [comment]
Hey Judy,

Thanks for reaching out. For affordances, we have provided pre-trained models [here](https://github.com/uiuc-robovision/hands-as-probes/tree/main/ACP#3-pretrained-models).
Then we have also provided scripts to run batch inference as mentioned in [this](https://github.com/uiuc-robovision/hands-as-probes/tree/main/ACP#inferring-using-a-pretrained-model) section (please look for custom directory command). We have also provided a notebook that can help you visualize these affordances [here](https://github.com/uiuc-robovision/hands-as-probes/blob/main/ACP/visualizations/hover_vis-clean_smooth.ipynb). 

Can you try downloading the model and then try to run our model on a set of images with the provided scripts.

Please let me know if you need any help with these or were you looking for some other specific pre-trained model that we have used in the paper.

**Comment by JudyYe** [comment]
Hi, Thank you for your detailed instruction. I was not aware of these before when skimming README. Thank you so much for your help!
